### Plantix - Plant Disease Prediction

In [25]:
# Importing libraries
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten #type: ignore
from tensorflow.keras.models import Sequential #type: ignore

##### Data Preprocessing

In [10]:
# Training image preprocessing
training_set = tf.keras.utils.image_dataset_from_directory(
    "C:/Users/Aadarsh/Desktop/Plantix/data/train",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


In [11]:
# Validation image preprocessing
validation_set = tf.keras.utils.image_dataset_from_directory(
    "C:/Users/Aadarsh/Desktop/Plantix/data/valid",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [12]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [13]:
validation_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [15]:
for x, y in training_set:
    print(x)
    print(y)
    break

tf.Tensor(
[[[[193.75 188.75 195.75]
   [198.5  193.5  200.5 ]
   [195.25 190.25 197.25]
   ...
   [165.   161.   175.  ]
   [155.25 151.25 165.25]
   [159.25 155.25 169.25]]

  [[195.25 190.25 197.25]
   [193.25 188.25 195.25]
   [193.75 188.75 195.75]
   ...
   [157.5  153.5  167.5 ]
   [160.75 156.75 170.75]
   [159.25 155.25 169.25]]

  [[198.   193.   200.  ]
   [189.75 184.75 191.75]
   [192.   187.   194.  ]
   ...
   [159.75 155.75 169.75]
   [158.25 154.25 168.25]
   [170.   166.   180.  ]]

  ...

  [[109.   130.75  59.75]
   [ 69.5   96.75  13.75]
   [ 76.75 110.5   14.5 ]
   ...
   [ 91.5  134.5   54.  ]
   [ 81.25 121.25  34.  ]
   [ 85.75 124.75  34.25]]

  [[ 98.   123.25  52.5 ]
   [ 68.    97.25  16.  ]
   [ 77.   111.5   21.  ]
   ...
   [ 90.25 133.75  51.25]
   [ 86.   126.25  37.  ]
   [ 92.25 131.25  38.75]]

  [[ 58.75  85.5   18.5 ]
   [ 67.75  98.    23.  ]
   [ 76.5  110.5   29.  ]
   ...
   [ 90.   133.5   49.  ]
   [ 92.   132.5   42.5 ]
   [ 97.75 137.25  4

##### Building Model

In [32]:
model = Sequential()

In [33]:
# Building Convolution Layer
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu", input_shape=[128, 128, 3])) #type: ignore
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

In [34]:
model.add(Conv2D(filters=64, kernel_size=3, padding="same", activation="relu", input_shape=[128, 128, 3])) #type: ignore
model.add(Conv2D(filters=64, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

In [35]:
model.add(Conv2D(filters=128, kernel_size=3, padding="same", activation="relu", input_shape=[128, 128, 3])) #type: ignore
model.add(Conv2D(filters=128, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

In [36]:
model.add(Conv2D(filters=256, kernel_size=3, padding="same", activation="relu", input_shape=[128, 128, 3])) #type: ignore
model.add(Conv2D(filters=256, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

In [37]:
model.add(Flatten())

In [38]:
model.add(Dense(units=1024, activation="relu"))

In [39]:
# Output Layer
model.add(Dense(units=38, activation="softmax"))

##### Compiling Model

In [40]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [41]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_11 (Conv2D)          (None, 128, 128, 32)      896       
                                                                 
 conv2d_12 (Conv2D)          (None, 128, 128, 32)      9248      
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 64, 64, 32)       0         
 2D)                                                             
                                                                 
 conv2d_13 (Conv2D)          (None, 64, 64, 64)        18496     
                                                                 
 conv2d_14 (Conv2D)          (None, 64, 64, 64)        36928     
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 32, 32, 64)       0         
 2D)                                                  

##### Training Model

In [42]:
training_history = model.fit(x=training_set, validation_data=validation_set, epochs=10)

Epoch 1/10
2197/2197 [==============================] - 214s 92ms/step - loss: 1.0680 - accuracy: 0.6797 - val_loss: 2.4313 - val_accuracy: 0.6815
Epoch 2/10
2197/2197 [==============================] - 199s 90ms/step - loss: 0.3326 - accuracy: 0.8904 - val_loss: 2.8930 - val_accuracy: 0.7019
Epoch 3/10
2197/2197 [==============================] - 200s 91ms/step - loss: 0.2193 - accuracy: 0.9270 - val_loss: 3.3499 - val_accuracy: 0.7122
Epoch 4/10
2197/2197 [==============================] - 195s 89ms/step - loss: 0.1776 - accuracy: 0.9408 - val_loss: 3.2367 - val_accuracy: 0.7147
Epoch 5/10
2197/2197 [==============================] - 194s 88ms/step - loss: 0.1461 - accuracy: 0.9512 - val_loss: 3.7338 - val_accuracy: 0.7296
Epoch 6/10
2197/2197 [==============================] - 192s 88ms/step - loss: 0.1321 - accuracy: 0.9570 - val_loss: 5.0905 - val_accuracy: 0.7466
Epoch 7/10
2197/2197 [==============================] - 192s 87ms/step - loss: 0.1254 - accuracy: 0.9597 - val_loss: 4